config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get 'api/about'
  get 'contact/index'
  post 'api/haiku'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  resources :event_categories
  resources :categories
  root 'home#index'
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event_category.rb
class EventCategory < ApplicationRecord
end

app/controllers/event_categories_controller.rb
class EventCategoriesController < ApplicationController
  before_action :set_event_category, only: [:show, :edit, :update, :destroy]

  # GET /event_categories
  # GET /event_categories.json
  def index
    @event_categories = EventCategory.all
  end

  # GET /event_categories/1
  # GET /event_categories/1.json
  def show
  end

  # GET /event_categories/new
  def new
    @event_category = EventCategory.new
  end

  # GET /event_categories/1/edit
  def edit
  end

  # POST /event_categories
  # POST /event_categories.json
  def create
    @event_category = EventCategory.new(event_category_params)

    respond_to do |format|
      if @event_category.save
        format.html { redirect_to @event_category, notice: 'Event category was successfully created.' }
        format.json { render :show, status: :created, location: @event_category }
      else
        format.html { render :new }
        format.json { render json: @event_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_categories/1
  # PATCH/PUT /event_categories/1.json
  def update
    respond_to do |format|
      if @event_category.update(event_category_params)
        format.html { redirect_to @event_category, notice: 'Event category was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_category }
      else
        format.html { render :edit }
        format.json { render json: @event_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_categories/1
  # DELETE /event_categories/1.json
  def destroy
    @event_category.destroy
    respond_to do |format|
      format.html { redirect_to event_categories_url, notice: 'Event category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_category
      @event_category = EventCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_category_params
      params.require(:event_category).permit(:event_id, :category_id)
    end
end

app/helpers/event_categories_helper.rb
module EventCategoriesHelper
end

app/views/event_categories/_form.html.erb
<%= form_with(model: event_category, local: true) do |form| %>
  <% if event_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_category.errors.count, "error") %> prohibited this event_category from being saved:</h2>

      <ul>
      <% event_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.number_field :event_id %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.number_field :category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_categories/edit.html.erb
<h1>Editing Event Category</h1>

<%= render 'form', event_category: @event_category %>

<%= link_to 'Show', @event_category %> |
<%= link_to 'Back', event_categories_path %>

app/views/event_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Categories</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_categories.each do |event_category| %>
      <tr>
        <td><%= event_category.event_id %></td>
        <td><%= event_category.category_id %></td>
        <td><%= link_to 'Show', event_category %></td>
        <td><%= link_to 'Edit', edit_event_category_path(event_category) %></td>
        <td><%= link_to 'Destroy', event_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Category', new_event_category_path %>

app/views/event_categories/new.html.erb
<h1>New Event Category</h1>

<%= render 'form', event_category: @event_category %>

<%= link_to 'Back', event_categories_path %>

app/views/event_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @event_category.event_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @event_category.category_id %>
</p>

<%= link_to 'Edit', edit_event_category_path(@event_category) %> |
<%= link_to 'Back', event_categories_path %>